import AppKit

/// Generates a formatted connection report for ISP troubleshooting.
/// "Show this to your internet provider." — the feature that sells the app.
final class ISPReport {
    private let eventLog: EventLog
    private let connectionQuality: ConnectionQuality

    init(eventLog: EventLog, connectionQuality: ConnectionQuality) {
        self.eventLog = eventLog
        self.connectionQuality = connectionQuality
    }

    /// Generate a plain-text report for the last N days
    func generateReport(days: Int = 7) -> String {
        let now = Date()
        let start = now.addingTimeInterval(-Double(days) * 86400)
        let events = eventLog.eventsInRange(from: start, to: now)
        let quality = connectionQuality.currentReport()

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "MMM d, yyyy"

        let timeFormatter = DateFormatter()
        timeFormatter.dateFormat = "MMM d, h:mm:ss a"

        let startStr = dateFormatter.string(from: start)
        let endStr = dateFormatter.string(from: now)

        // Compute per-network stats
        let networks = eventLog.knownNetworks()
        var networkStats: [(ssid: String, uptime: Double, disconnects: Int)] = []
        for ssid in networks {
            let stats = connectionQuality.networkReliability(ssid: ssid, days: days)
            networkStats.append((ssid: ssid, uptime: stats.uptime, disconnects: stats.disconnects))
        }
        networkStats.sort { $0.disconnects > $1.disconnects }

        // Disconnects by day
        let disconnects = events.filter { $0.type == .disconnected }
        var dayBuckets = [String: Int]()
        let dayFormatter = DateFormatter()
        dayFormatter.dateFormat = "EEE, MMM d"
        for event in disconnects {
            let key = dayFormatter.string(from: event.timestamp)
            dayBuckets[key, default: 0] += 1
        }

        // Disconnects by hour
        var hourBuckets = [Int: Int]()
        let calendar = Calendar.current
        for event in disconnects {
            let hour = calendar.component(.hour, from: event.timestamp)
            hourBuckets[hour, default: 0] += 1
        }

        // Build outage timeline
        var outages: [(start: Date, end: Date?, duration: TimeInterval, ssid: String?)] = []
        var lastDisconnect: (date: Date, ssid: String?)?
        let sorted = events.sorted { $0.timestamp < $1.timestamp }
        for event in sorted {
            if event.type == .disconnected {
                lastDisconnect = (event.timestamp, event.ssid)
            } else if event.type == .connected, let disc = lastDisconnect {
                let duration = event.timestamp.timeIntervalSince(disc.date)
                outages.append((start: disc.date, end: event.timestamp, duration: duration, ssid: disc.ssid))
                lastDisconnect = nil
            }
        }
        if let disc = lastDisconnect {
            let duration = now.timeIntervalSince(disc.date)
            outages.append((start: disc.date, end: nil, duration: duration, ssid: disc.ssid))
        }

        let totalDowntime = outages.reduce(0.0) { $0 + $1.duration }
        let longestOutage = outages.max(by: { $0.duration < $1.duration })?.duration ?? 0
        let avgOutage = outages.isEmpty ? 0 : totalDowntime / Double(outages.count)

        // Build the report
        var report = """
            ╔══════════════════════════════════════════════════════════╗
            ║           WIFI CONNECTION REPORT                        ║
            ║           Generated by Dropout for macOS                ║
            ╚══════════════════════════════════════════════════════════╝

            Period:          \(startStr) — \(endStr) (\(days) days)
            Connection Grade: \(quality.grade.rawValue) (\(quality.score)/100)
            Total Disconnects: \(disconnects.count)
            Total Downtime:   \(formatDuration(totalDowntime))
            Longest Outage:   \(formatDuration(longestOutage))
            Average Outage:   \(formatDuration(avgOutage))

            """

        // Network reliability
        if !networkStats.isEmpty {
            report += """

                ── NETWORK RELIABILITY ─────────────────────────────────────

                """
            for net in networkStats {
                let uptimeStr = String(format: "%.1f%%", net.uptime)
                report += "  \(net.ssid.padding(toLength: 28, withPad: " ", startingAt: 0)) \(uptimeStr.padding(toLength: 8, withPad: " ", startingAt: 0)) uptime   \(net.disconnects) drops\n"
            }
        }

        // Daily breakdown
        if !dayBuckets.isEmpty {
            report += """

                ── DISCONNECTS BY DAY ──────────────────────────────────────

                """
            // Sort by date order (approximate — using the formatted string)
            let sortedDays = dayBuckets.sorted { $0.value > $1.value }
            for (day, count) in sortedDays {
                let bar = String(repeating: "█", count: min(count, 40))
                report += "  \(day.padding(toLength: 16, withPad: " ", startingAt: 0)) \(String(count).padding(toLength: 4, withPad: " ", startingAt: 0)) \(bar)\n"
            }
        }

        // Hourly pattern
        if !hourBuckets.isEmpty {
            report += """

                ── PEAK DROP TIMES ─────────────────────────────────────────

                """
            for hour in 0..<24 {
                let count = hourBuckets[hour] ?? 0
                guard count > 0 else { continue }
                let label = hour == 0 ? "12 AM" : hour < 12 ? "\(hour) AM" : hour == 12 ? "12 PM" : "\(hour-12) PM"
                let bar = String(repeating: "█", count: min(count, 40))
                report += "  \(label.padding(toLength: 8, withPad: " ", startingAt: 0)) \(String(count).padding(toLength: 4, withPad: " ", startingAt: 0)) \(bar)\n"
            }
        }

        // Outage timeline (last 20)
        let recentOutages = outages.suffix(20)
        if !recentOutages.isEmpty {
            report += """

                ── OUTAGE TIMELINE (MOST RECENT) ───────────────────────────

                """
            for outage in recentOutages.reversed() {
                let startTime = timeFormatter.string(from: outage.start)
                let duration = formatDuration(outage.duration)
                let network = outage.ssid ?? "Unknown"
                let status = outage.end == nil ? "(ongoing)" : ""
                report += "  \(startTime)  \(duration.padding(toLength: 12, withPad: " ", startingAt: 0)) \(network) \(status)\n"
            }
        }

        report += """

            ── ABOUT THIS REPORT ───────────────────────────────────────

              Generated by SignalDrop — WiFi disconnect notifier for macOS
              https://github.com/MeriaApp/dropout

              This report was generated from locally-stored WiFi event data.
              No data was transmitted to generate this report.

            ════════════════════════════════════════════════════════════
            """

        return report
    }

    /// Save report via NSSavePanel
    func saveReport(days: Int = 7) {
        let report = generateReport(days: days)
        let savePanel = NSSavePanel()
        savePanel.allowedContentTypes = [.plainText]
        savePanel.nameFieldStringValue = "WiFi-Connection-Report.txt"
        savePanel.canCreateDirectories = true
        savePanel.title = "Save WiFi Connection Report"

        savePanel.begin { response in
            guard response == .OK, let url = savePanel.url else { return }
            try? report.write(to: url, atomically: true, encoding: .utf8)
            // Open the file so the user sees it immediately
            NSWorkspace.shared.open(url)
        }
    }

    private func formatDuration(_ seconds: TimeInterval) -> String {
        if seconds < 60 {
            return "\(Int(seconds))s"
        } else if seconds < 3600 {
            let mins = Int(seconds) / 60
            let secs = Int(seconds) % 60
            return secs > 0 ? "\(mins)m \(secs)s" : "\(mins)m"
        } else {
            let hours = Int(seconds) / 3600
            let mins = (Int(seconds) % 3600) / 60
            return mins > 0 ? "\(hours)h \(mins)m" : "\(hours)h"
        }
    }
}
